name: pub_1290_lib
version: 0.0.1
description: A sample command-line application.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  di: any
  intl: any
  js_mimicry: ">=0.2.0 <0.3.0"
  dom_stub: '>=0.0.1 <0.1.0'
  observe: '^0.13.1'
transformers:
- js_mimicry
- dom_stub:
      imports: { '../browser_common.dart': '../vm_common.dart' , 'browser_common.dart': 'vm_common.dart' }
- pub_1290_lib/version/transformer:
    files:
    - lib/api_request.dart
- observe
- pub_1290_lib/transformer
- pub_1290_lib/smoke/transformer
- test/pub_serve:
    $include: test/**_test{.*,}.dart
dev_dependencies:
  barback: any
  smoke: any
  test: '>=0.12.0'
  mockito: "^0.10.1"

